### ISSUE TITLE
When moving from 0.4.28 to 0.5.1, wrapper.py run produces an error when using test data.

### ISSUE THREAD

**Issue by pcm32** [ISA-tools/mzml2isa-galaxy#6]
Hi there!

We recently moved our container from 0.4.28 to 0.5.1 version of mzml2isa, only by changing the version used in pip install (see [commit](https://github.com/phnmnl/container-mzml2isa/commit/681bb430192daba9d3aace45e34d365939440c49)). When running wrapper.py with the test data available in this repo, it now fails like this:

```
/usr/local/lib/python2.7/dist-packages/mzml2isa/utils.py:267: UserWarning: Could not use latest online MS ontology, using local (version [u'4.0.1'])
  "using local (version {})".format(obo.meta['version']))
/usr/local/lib/python2.7/dist-packages/mzml2isa/utils.py:274: UserWarning: Could not use latest online IMS ontology, using local (version [u'0.9.1'])
  "using local (version {})".format(obo.meta['version']))
Traceback (most recent call last):
  File "/usr/local/bin/wrapper.py", line 235, in <module>
    main()
  File "/usr/local/bin/wrapper.py", line 215, in main
    multip=False)
  File "/usr/local/lib/python2.7/dist-packages/mzml2isa/parsing.py", line 231, in full_parse
    convert(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mzml2isa/parsing.py", line 121, in convert
    meta_loader = UserMetaLoader(kwargs.get('usermeta', None))
  File "/usr/local/lib/python2.7/dist-packages/mzml2isa/usermeta.py", line 322, in __init__
    elif usermeta_token.endswith('.xlsx'):
AttributeError: 'dict' object has no attribute 'endswith'
```

Commands invoked for testing are [here](https://github.com/phnmnl/container-mzml2isa/blob/6165f14e1b42ccec903d9031aa63118b60232170/runTest1.sh). Any suggestions?

Thanks!
Pablo

**Comment by Tomnl** [comment]
This is now fixed in https://github.com/ISA-tools/mzml2isa-galaxy/pull/11
